spring:
  application:
    name: order-service
    
    rabbitmq:
    host: http://127.0.0.1/
    port: 15672
    username: guest
    password: guest
    
# server:
#  port: 8201
  
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
---
spring:
  profiles: order1
  
server:
  port: 8201
  
---
spring:
  profiles: order2
  
server:
  port: 8202